name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.5'
      - run: npm install
      - run: yarn install
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Build and run tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      - name: Installing libpq
        run: |
          sudo apt-get -yqq install libpq-dev

      - name: Installing bundler
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Prepare rails db
        run: |
          bundle exec rails db:prepare

      - name: Run tests
        run: |
          bundle exec rails test
